name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch where new changes are committed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Deploy to build branch
        run: |
          git config --global user.name 'tanzid64'
          git config --global user.email 'tanzid@inbox.ru'
          git checkout --orphan build  # Create or switch to the build branch
          git --work-tree ./dist add --all  # Add dist folder contents to the build branch
          git --work-tree ./dist commit -m "Deploy to build branch"
          git push origin build --force  # Push to the build branch forcefully
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub will automatically provide this
